# docker-compose.yml
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: healthconnect-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: healthconnect-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/healthconnect?authSource=admin
      - JWT_SECRET=dev_jwt_secret
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: healthconnect-frontend
    restart: always
    ports:
      - "5173:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongodb_data: